language: node_js

node_js:
    - "node"
    - "12"
    - "14"

sudo: false

addons:
  chrome: stable

git:
    submodules: false


before_script:
    - npm install
    - npm install -g @angular/cli
    - export CHROME_BIN=usr/bin/google-chrome

cache:
  directories:
     - ./node_modules


script:
    - npm run test --watch=false --no-watch --no-progress --browsers=ChromeHeadlessCI
    # - npm test --browsers=ChromeHeadlessCI
    # - ./node_modules/.bin/karma start --browsers Firefox --single-run

after_success:
    - npm run report-coveralls
    - npm run report-codecov
