language: node_js

node_js:
    - "node"
    - "12"
    - "14"

sudo: false

git:
    submodules: false

before_script:
    - npm install
    - npm install -g @angular/cli

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
