language: node_js

node_js:
    - "node"
    - "12"
    - "14"

sudo: false

git:
    submodules: false

before_script:
    - npm install
    - npm install -g @angular/cli
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules


script:
    - npm test --browsers=ChromeHeadlessCI

after_success:
    - npm run report-coveralls
    - npm run report-codecov
