language: node_js

node_js:
    - "node"
    - "12"
    - "14"

sudo: false

git:
    submodules: false

before-install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
    - npm install
    - npm install -g @angular/cli

addons:
  chrome: stable


script:
    - npm test --browsers=ChromeHeadlessCI

after_success:
    - npm run report-coveralls
    - npm run report-codecov
