language: node_js

node_js:
    - "node"
    - "12"
    - "14"

sudo: false

addons:
  chrome: stable

git:
    submodules: false

before-install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost 

before_script:
    - npm install
    - npm install -g @angular/cli

cache:
  directories:
     - ./node_modules


script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
