language: node_js

node_js:
    - "node"
    - "12"
    - "14"

sudo: false

dist: xenial
services:
  - xvfb

addons:
  firefox: "49.0"

git:
    submodules: false


before_script:
    - npm install
    - npm install -g @angular/cli



cache:
  directories:
     - ./node_modules


script:
    - npm test --watch=false --no-progress --single-run

after_success:
    - npm run report-coveralls
    - npm run report-codecov
