language: node_js

node_js:
    - "node"
    - "12"
    - "14"

sudo: false

addons:
  chrome: stable

git:
    submodules: false


before_script:
    - npm install
    - npm install -g @angular/cli
    - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
    - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
    - unzip chromedriver_linux64.zip -d ~/bin


cache:
  directories:
     - ./node_modules


script:
    - npm test --no-watch --no-progress --browsers=ChromeHeadlessCI
    # - npm test --browsers=ChromeHeadlessCI
    # - ./node_modules/.bin/karma start --browsers Firefox --single-run

after_success:
    - npm run report-coveralls
    - npm run report-codecov
